r"""Generate Scriber's vector-backed Windows app and tray identity.

Windows executables and taskbar buttons consume ICO resources rather than SVG
files.  This generator wraps the canonical feather from
``Frontend/client/public/favicon.svg`` in the contrast-safe white disc, saves
that exact vector as the app's dark-surface mark, renders every ICO frame
independently through Tauri's local SVG renderer, and emits native tray rasters
for Windows display scaling from 100 through 300 percent.

Run from the repository root:

    venv\Scripts\python.exe scripts\generate_windows_app_icon.py
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path
import re
import shutil
import struct
import subprocess
import tempfile
import xml.etree.ElementTree as ET

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parents[1]
FRONTEND_ROOT = REPO_ROOT / "Frontend"
SOURCE_SVG = FRONTEND_ROOT / "client" / "public" / "favicon.svg"
DARK_APP_SVG = FRONTEND_ROOT / "client" / "public" / "favicon-dark.svg"
ICON_DIR = FRONTEND_ROOT / "src-tauri" / "icons"
MASTER_SVG = ICON_DIR / "windows-app-icon.svg"
WINDOWS_ICO = ICON_DIR / "icon.ico"
TRAY_PNG = ICON_DIR / "tray-normal.png"
TRAY_RGBA = ICON_DIR / "tray-normal.rgba"
WINDOW_PNG = ICON_DIR / "window-icon.png"
WINDOW_RGBA = ICON_DIR / "window-icon.rgba"
TAURI_CLI = FRONTEND_ROOT / "node_modules" / "@tauri-apps" / "cli" / "tauri.js"

ICON_SIZES = (16, 24, 32, 48, 64, 128, 256)
# Windows' notification area is nominally 16 logical pixels. These native
# raster sizes cover 100-300% display scaling without asking Explorer to
# resample a single 32 px source.
TRAY_SIZES = (16, 20, 24, 28, 32, 36, 40, 48)
MASTER_SIZE = 256
# Keep both the lower-left pen tip and the right tail a few pixels inside the
# disc while maximizing the unchanged canonical paths around that visual anchor.
FEATHER_BOX_WIDTH = 236.0
FEATHER_OPTICAL_OFFSET_X = 9.5
FEATHER_OPTICAL_OFFSET_Y = -8.0


def _number(value: float) -> str:
    return f"{value:.10f}".rstrip("0").rstrip(".")


def _build_master_svg() -> bytes:
    source = SOURCE_SVG.read_text(encoding="utf-8")
    root = ET.fromstring(source)
    view_box = [float(value) for value in root.attrib["viewBox"].split()]
    if len(view_box) != 4 or view_box[2] <= 0 or view_box[3] <= 0:
        raise ValueError(f"Invalid source viewBox: {root.attrib['viewBox']!r}")

    styles: dict[str, str] = {}
    for style in (
        element.text or "" for element in root.iter() if element.tag.endswith("style")
    ):
        styles.update(
            (name, fill.upper())
            for name, fill in re.findall(
                r"\.([A-Za-z0-9_-]+)\s*\{[^}]*?fill\s*:\s*(#[0-9A-Fa-f]{6})",
                style,
            )
        )

    paths: list[str] = []
    for element in root.iter():
        if not element.tag.endswith("path"):
            continue
        path_data = element.attrib.get("d")
        class_name = element.attrib.get("class")
        fill = element.attrib.get("fill") or styles.get(class_name or "")
        if not path_data or not fill:
            raise ValueError("Every source feather path must have path data and a fill color")
        paths.append(
            f'    <path fill="{html.escape(fill, quote=True)}" '
            f'd="{html.escape(path_data, quote=True)}"/>'
        )
    if not paths:
        raise ValueError("No feather paths found in the canonical SVG")

    source_x, source_y, source_width, source_height = view_box
    scale = FEATHER_BOX_WIDTH / source_width
    rendered_height = source_height * scale
    offset_x = (MASTER_SIZE - FEATHER_BOX_WIDTH) / 2 + FEATHER_OPTICAL_OFFSET_X
    offset_y = (MASTER_SIZE - rendered_height) / 2 + FEATHER_OPTICAL_OFFSET_Y
    transform = (
        f"translate({_number(offset_x)} {_number(offset_y)}) "
        f"scale({_number(scale)}) "
        f"translate({_number(-source_x)} {_number(-source_y)})"
    )

    document = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {MASTER_SIZE} {MASTER_SIZE}" width="{MASTER_SIZE}" height="{MASTER_SIZE}">
  <!-- Generated by scripts/generate_windows_app_icon.py from client/public/favicon.svg. -->
  <defs>
    <filter id="disc-shadow" x="-15%" y="-15%" width="130%" height="135%" color-interpolation-filters="sRGB">
      <feGaussianBlur stdDeviation="4"/>
    </filter>
  </defs>
  <circle cx="128" cy="131" r="120" fill="#253037" opacity="0.2" filter="url(#disc-shadow)"/>
  <circle cx="128" cy="128" r="120" fill="#FFFFFF"/>
  <g transform="{transform}">
{chr(10).join(paths)}
  </g>
</svg>
'''
    return document.encode("utf-8")


def _render_frames(master_svg: bytes, output_dir: Path) -> dict[int, bytes]:
    node = shutil.which("node")
    if not node:
        raise RuntimeError("Node.js is required to run Tauri's local SVG renderer")
    if not TAURI_CLI.is_file():
        raise RuntimeError(
            "Tauri CLI is not installed; run npm install in Frontend before regenerating icons"
        )

    source_path = output_dir / "windows-app-icon.svg"
    source_path.write_bytes(master_svg)
    png_dir = output_dir / "png"
    png_dir.mkdir()
    frames: dict[int, bytes] = {}
    for size in sorted(set(ICON_SIZES + TRAY_SIZES)):
        subprocess.run(
            [
                node,
                str(TAURI_CLI),
                "icon",
                "--png",
                str(size),
                "--output",
                str(png_dir),
                str(source_path),
            ],
            cwd=FRONTEND_ROOT,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        frame = (png_dir / f"{size}x{size}.png").read_bytes()
        if frame[:8] != b"\x89PNG\r\n\x1a\n":
            raise ValueError(f"Tauri did not produce a PNG for the {size}px frame")
        width, height = struct.unpack_from(">II", frame, 16)
        if (width, height) != (size, size):
            raise ValueError(f"Expected a {size}px frame, got {width}x{height}")
        frames[size] = frame
    return frames


def _build_ico(frames: dict[int, bytes]) -> bytes:
    directory_size = 6 + 16 * len(ICON_SIZES)
    offset = directory_size
    entries: list[bytes] = []
    payloads: list[bytes] = []
    for size in ICON_SIZES:
        payload = frames[size]
        dimension = 0 if size == 256 else size
        entries.append(
            struct.pack(
                "<BBBBHHII",
                dimension,
                dimension,
                0,
                0,
                1,
                32,
                len(payload),
                offset,
            )
        )
        payloads.append(payload)
        offset += len(payload)
    return struct.pack("<HHH", 0, 1, len(ICON_SIZES)) + b"".join(entries + payloads)


def _rgba_bytes(frame: bytes, size: int, name: str, work_dir: Path) -> bytes:
    path = work_dir / name
    path.write_bytes(frame)
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        if rgba.size != (size, size):
            raise ValueError(f"Expected a {size}x{size} frame, got {rgba.size}")
        return rgba.tobytes()


def _check_file(path: Path, expected: bytes) -> bool:
    return path.is_file() and path.read_bytes() == expected


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the checked-in SVG, ICO, tray, and window assets are current",
    )
    args = parser.parse_args()

    master_svg = _build_master_svg()
    with tempfile.TemporaryDirectory(prefix="scriber-windows-icon-") as temporary:
        work_dir = Path(temporary)
        frames = _render_frames(master_svg, work_dir)
        icon = _build_ico(frames)
        tray_frames = {
            size: (
                frames[size],
                _rgba_bytes(frames[size], size, f"tray-normal-{size}.png", work_dir),
            )
            for size in TRAY_SIZES
        }
        tray_png, tray_rgba = tray_frames[32]
        window_png = frames[256]
        window_rgba = _rgba_bytes(window_png, 256, "window-icon.png", work_dir)

    artifacts = {
        DARK_APP_SVG: master_svg,
        MASTER_SVG: master_svg,
        WINDOWS_ICO: icon,
        TRAY_PNG: tray_png,
        TRAY_RGBA: tray_rgba,
        WINDOW_PNG: window_png,
        WINDOW_RGBA: window_rgba,
    }
    for size, (png, rgba) in tray_frames.items():
        artifacts[ICON_DIR / f"tray-normal-{size}.rgba"] = rgba
    if args.check:
        stale = [
            str(path.relative_to(REPO_ROOT))
            for path, data in artifacts.items()
            if not _check_file(path, data)
        ]
        if stale:
            raise SystemExit("Stale Windows icon artifacts: " + ", ".join(stale))
        print("Windows SVG, ICO, tray, and window artifacts are current.")
        return

    for path, data in artifacts.items():
        path.write_bytes(data)
    sizes = ", ".join(f"{size}px" for size in ICON_SIZES)
    print(f"Generated native ICO frames: {sizes}")


if __name__ == "__main__":
    main()
